[2025/03/23 19:58:56 hloc INFO] Extracting local features with configuration:
{'device': 'cuda',
 'model': {'name': 'netvlad'},
 'output': 'global-feats-netvlad',
 'preprocessing': {'resize_max': 1024}}
[2025/03/23 19:58:56 hloc INFO] Skipping the extraction.
[2025/03/23 19:58:56 hloc INFO] Extracting image pairs from a retrieval database.
Using device: cuda
Example subset of reference paths: []

[Step 4] Global retrieval feature extraction + pairs_from_retrieval
Traceback (most recent call last):
  File "/home/siyanhu/Gits/Tramway/Hierarchical-Localization/nohup_scripts/run_recon.py", line 143, in <module>
    main()
  File "/home/siyanhu/Gits/Tramway/Hierarchical-Localization/nohup_scripts/run_recon.py", line 102, in main
    pairs_from_retrieval.main(retrieval_path, sfm_pairs_path, num_matched=number_of_match)
  File "/home/siyanhu/Gits/Tramway/Hierarchical-Localization/hloc/pairs_from_retrieval.py", line 93, in main
    name2db = {n: i for i, p in enumerate(db_descriptors) for n in list_h5_names(p)}
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siyanhu/Gits/Tramway/Hierarchical-Localization/hloc/pairs_from_retrieval.py", line 93, in <dictcomp>
    name2db = {n: i for i, p in enumerate(db_descriptors) for n in list_h5_names(p)}
                                                                   ^^^^^^^^^^^^^^^^
  File "/home/siyanhu/Gits/Tramway/Hierarchical-Localization/hloc/utils/io.py", line 26, in list_h5_names
    with h5py.File(str(path), "r", libver="latest") as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siyanhu/miniconda3/envs/py311hloc/lib/python3.11/site-packages/h5py/_hl/files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/siyanhu/miniconda3/envs/py311hloc/lib/python3.11/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/media/siyanhu/Changkun/Siyan/Tramway/process/20250124_lidarcam/rbg1/features_retrieval.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
